// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuJLqbkt8wUmBhZ6-6COeQPs-1oZn5ec',
    appId: '1:184463524483:web:3f703233a54cfe16b111b6',
    messagingSenderId: '184463524483',
    projectId: 'student-support-system-flutter',
    authDomain: 'student-support-system-flutter.firebaseapp.com',
    storageBucket: 'student-support-system-flutter.firebasestorage.app',
    measurementId: 'G-QC2HEKMF26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBanlyEZ_ph1clL4_szpLkyX52KnzTgvIU',
    appId: '1:184463524483:android:7e0c554d5eebda1bb111b6',
    messagingSenderId: '184463524483',
    projectId: 'student-support-system-flutter',
    storageBucket: 'student-support-system-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_TUoBLrLT3q26LVvelqzJZy78u4GahJY',
    appId: '1:184463524483:ios:881e2682a2b45b7ab111b6',
    messagingSenderId: '184463524483',
    projectId: 'student-support-system-flutter',
    storageBucket: 'student-support-system-flutter.firebasestorage.app',
    iosBundleId: 'com.example.studentsupportsystem',
  );
}
